server:
  port: 9010
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: byapi-interface
          uri: http://localhost:9020
          predicates:
            - Path=/**
  redis:
    host: localhost
    port: 6379



dubbo:
  application:
    name: consumer
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
